id: P8C7E5F07
initial_creation_type: input
source_metadata:
  title: Abhidharma
  parent: 1. Commentaries on the Eighteen Great Treatises
  source: https://sakyalibrary.com
  bases:
    d25b:
      title: ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: འཕགས་པ་ཐོགས་མེད།
      base_file: d25b.txt
      order: 1
    75d9:
      title: དམ་པའི་ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་པའི་སྙིང་པོ་ལེགས་བཤད་ནོར་བུའི་ཕྲེང་བ།
      author: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
      base_file: 75d9.txt
      order: 2
    d603:
      title: ཕུང་ཁམས་སྐྱེ་མཆེད་ཀྱི་རྣམ་གཞག་ཇི་སྙེད་ཤེས་བྱའི་སྒོ་འབྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: d603.txt
      order: 3
    70df:
      title: དམ་པའི་ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་པའི་འགྲེལ་བ་ཤེས་བྱ་རབ་གསལ་སྣང་བ་ཞེས་བྱ་བ།
      author: ས་བཟང་འཇམ་དབྱངས་བློ་གྲོས།
      base_file: 70df.txt
      order: 4
    dfd2:
      title: ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་ཀྱི་རྒྱ་ཆེར་འགྲེལ་པ་ཤེས་བྱ་གསལ་བྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: དཔངས་ལོ་བློ་གྲོས་བརྟན་པ།
      base_file: dfd2.txt
      order: 5
    fbc0:
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་ཚིག་ལེའུར་བྱས་པ་བཞུགས་སོ།།
      author: སློབ་དཔོན་དབྱིག་གཉེན།
      base_file: fbc0.txt
      order: 6
    9ec6:
      title: མངོན་པ་མཛོད་ཀྱི་བཤད་པ་བཞུགས་སོ།།་་་་་རང་འགྲེལ།
      author: སློབ་དཔོན་དབྱིག་གཉེན།
      base_file: 9ec6.txt
      order: 7
    b476:
      title: ཆོས་མངོན་པ་གསལ་བྱེད་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མཆིམས་ཆུང་བ་བློ་བཟང་གྲགས་པ།
      base_file: b476.txt
      order: 8
    4b05:
      title: ཆོས་མངོན་པ་མཛོད་ཀྱི་བཤད་ཐབས་མན་ངག་ངོ་མཚར་གསུམ་ལྡན་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 4b05.txt
      order: 9
    acb3:
      title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་གཞུང་དོན་རབ་ཏུ་གསལ་བའི་ཉི་མ་ཞེས་བྱ་བ།་་་་ཀུན་མཁྱེན་བཀའ་འབུམ་ཁ་སྐོང་ལས།
      author: མུས་ཆེན་ཐུགས་རྗེ་དཔལ་བཟང་།
      base_file: acb3.txt
      order: 10
    53c0:
      title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་སྤྱི་དོན་ཇི་སྙེད་ཤེས་བྱའི་གསལ་བྱེད་ངག་གི་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: 53c0.txt
      order: 11
    a0e6:
      title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ།
      author: བོ་དོང་ཕྱོགས་ལས་རྣམ་རྒྱལ།
      base_file: a0e6.txt
      order: 12
    6d7b:
      title: ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་ཚིག་དོན་རབ་གསལ།
      author: དངོས་གྲུབ་དཔལ་འབར།
      base_file: 6d7b.txt
      order: 13
created_at: '2022-04-06T15:54:58.442397'
last_modified_at: '2022-04-06T15:54:58.442404'
